### ISSUE TITLE
Refactor Roadmap

### ISSUE THREAD

**Issue by JeffersonQin** [JeffersonQin/lightnovel_epub#1]
* Load & Store Architecture
  - [x] 将原来的 cli 也设计成可以 dump 的
  - [x] 给原来的 cli 设计 dump 目录
  - [x] 图片不要下在 temp path
  - [x] 每下完一张图片就替换掉 src 然后 dump 新的 html
  - [x] 将 download_image 从 write_epub 中分离，write_epub 只接受本地 image
  - [x] 给原来的 cli 添加 html-dump
